/**
 * PHYSICS.md §9, small-delta-eta stability: the §2.3 sum-to-product forms must
 * agree with a high-precision reference across deltaEta ∈ [1e-12, 1]. The
 * reference is a 50-digit mpmath table (hyperbolic.golden.ts), regenerated by
 * tools/physics-reference/generate_hyperbolic_golden.py.
 */
import fc from 'fast-check';
import { describe, expect, it } from 'vitest';

import { coshDifference, sinhDifference } from './hyperbolic.ts';
import { HYPERBOLIC_GOLDEN } from './hyperbolic.golden.ts';

const relError = (actual: number, expected: number): number =>
  expected === 0 ? Math.abs(actual) : Math.abs(actual - expected) / Math.abs(expected);

describe('stable forms vs the 50-digit reference', () => {
  it('matches every golden row within 2e-14 relative', () => {
    expect(HYPERBOLIC_GOLDEN.length).toBeGreaterThan(100);
    for (const row of HYPERBOLIC_GOLDEN) {
      expect(relError(sinhDifference(row.eta0, row.deltaEta), row.sinhDifference),
        `sinh eta0=${row.eta0} dEta=${row.deltaEta}`).toBeLessThanOrEqual(2e-14);
      expect(relError(coshDifference(row.eta0, row.deltaEta), row.coshDifference),
        `cosh eta0=${row.eta0} dEta=${row.deltaEta}`).toBeLessThanOrEqual(2e-14);
    }
  });

  it('the naive difference really does fail where the table looks — the test is not vacuous', () => {
    const row = HYPERBOLIC_GOLDEN.find((r) => r.eta0 === 1 && r.deltaEta === 1e-12);
    expect(row).toBeDefined();
    if (!row) return;
    const naive = Math.sinh(row.eta0 + row.deltaEta) - Math.sinh(row.eta0);
    expect(relError(naive, row.sinhDifference)).toBeGreaterThan(1e-9);
  });
});

describe('stable and naive forms agree where cancellation is absent', () => {
  it('cross-validates for deltaEta ≥ 0.25', () => {
    fc.assert(
      fc.property(
        // eta0 ≥ 0.5 keeps the interval clear of zero, where the naive cosh
        // difference cancels even at large deltaEta and would fail the compare.
        fc.double({ min: 0.5, max: 10, noNaN: true }),
        fc.double({ min: 0.25, max: 2, noNaN: true }),
        (eta0, deltaEta) => {
          const naiveSinh = Math.sinh(eta0 + deltaEta) - Math.sinh(eta0);
          const naiveCosh = Math.cosh(eta0 + deltaEta) - Math.cosh(eta0);
          expect(relError(sinhDifference(eta0, deltaEta), naiveSinh)).toBeLessThanOrEqual(1e-12);
          expect(relError(coshDifference(eta0, deltaEta), naiveCosh)).toBeLessThanOrEqual(1e-12);
        },
      ),
    );
  });
});
