# Emits packages/physics/src/hyperbolic.golden.ts: correctly rounded f64 values
# of sinh/cosh differences from a 50-digit mpmath reference. Build-time developer
# tool; never ships. Run from the repo root:
#
#   uv run --no-project --with mpmath python tools/physics-reference/generate_hyperbolic_golden.py
#
# The grid deliberately reaches deltaEta = 1e-12, where the naive difference of
# hyperbolics keeps only ~4 correct digits (PHYSICS.md §2.3, §9 small-delta-eta).
from pathlib import Path

from mpmath import cosh, mp, mpf, sinh

mp.dps = 50

ETA0 = [-10.0, -1.0, 0.0, 0.1, 1.0, 1.849, 5.0, 10.0, 15.0]
DELTA = [10.0**-e for e in range(12, 0, -1)] + [0.5, 1.0]

rows = []
for eta0 in ETA0:
    for delta in DELTA:
        e0, d = mpf(eta0), mpf(delta)
        sinh_diff = float(sinh(e0 + d) - sinh(e0))
        cosh_diff = float(cosh(e0 + d) - cosh(e0))
        rows.append(
            f'  {{ eta0: {eta0!r}, deltaEta: {delta!r}, '
            f'sinhDifference: {sinh_diff!r}, coshDifference: {cosh_diff!r} }},'
        )

out = Path(__file__).resolve().parents[2] / 'packages' / 'physics' / 'src' / 'hyperbolic.golden.ts'
out.write_text(
    '// Generated by tools/physics-reference/generate_hyperbolic_golden.py — do not edit.\n'
    '// Each value is the correctly rounded f64 of the true difference, computed at\n'
    '// 50 decimal digits with mpmath.\n'
    'export interface HyperbolicGoldenRow {\n'
    '  readonly eta0: number;\n'
    '  readonly deltaEta: number;\n'
    '  readonly sinhDifference: number;\n'
    '  readonly coshDifference: number;\n'
    '}\n\n'
    'export const HYPERBOLIC_GOLDEN: readonly HyperbolicGoldenRow[] = [\n'
    + '\n'.join(rows)
    + '\n];\n',
    encoding='utf-8',
)
print(f'wrote {out} ({len(rows)} rows)')
